#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
playground_dir="${repo_root}/.playground"
overwrite=0

if [[ "${1:-}" == "--force" ]]; then
  overwrite=1
elif [[ $# -gt 0 ]]; then
  echo "usage: $0 [--force]" >&2
  exit 2
fi

mkdir -p \
  "${playground_dir}/bibliography" \
  "${playground_dir}/build" \
  "${playground_dir}/data" \
  "${playground_dir}/figures/generated" \
  "${playground_dir}/preamble" \
  "${playground_dir}/scripts" \
  "${playground_dir}/tables"

copy_if_needed() {
  local source_path="$1"
  local destination_path="$2"

  if [[ -e "${destination_path}" && "${overwrite}" -eq 0 ]]; then
    return
  fi

  cp "${source_path}" "${destination_path}"
}

write_if_needed() {
  local destination_path="$1"

  if [[ -e "${destination_path}" && "${overwrite}" -eq 0 ]]; then
    cat >/dev/null
    return
  fi

  cat >"${destination_path}"
}

copy_if_needed "${repo_root}/src/preamble/packages.tex" "${playground_dir}/preamble/packages.tex"
copy_if_needed "${repo_root}/src/preamble/macros.tex" "${playground_dir}/preamble/macros.tex"

write_if_needed "${playground_dir}/Makefile" <<'EOF'
all: example-figure
	latexmk -C -output-directory=build examples.tex
	latexmk -pdf -synctex=1 -interaction=nonstopmode -output-directory=build examples.tex

example-figure:
	python scripts/generate_example_figure.py

clean:
	latexmk -C -output-directory=build examples.tex
	rm -rf build
EOF

write_if_needed "${playground_dir}/examples.tex" <<'EOF'
\documentclass[12pt]{report}

\input{preamble/packages}
\input{preamble/macros}

\begin{document}

\chapter{Example Writing Patterns}

This local playground is a compact style reference for common dissertation
elements: figures, equations, tables, citations, and cross-references. The
examples are intentionally written in a dissertation-like voice so the source
can be copied directly into a chapter and then adapted to the specific
analysis.

\section{Narrative and Citation Pattern}

Technical prose should do three jobs at once: define the measurement target,
state the modeling choice, and cite only the sources that carry conceptual
weight. Detector-response studies in high-energy physics are commonly built on
the Geant4 simulation toolkit~\cite{agostinelli2003geant4}, while offline
reconstruction and statistical analysis are often organized in
ROOT~\cite{brun1997root}. General conventions for reporting detector
performance and measurement uncertainties follow the treatment in
Ref.~\cite{knoll2010radiation}. In practice, those references should appear when
the tool or concept is first introduced rather than being repeated in every
subsection.

For the present example, the fractional energy resolution is parameterized as
\begin{equation}
R(E) = \sqrt{\left(\frac{a}{\sqrt{E}}\right)^2 + b^2},
\label{eq:example-resolution-model}
\end{equation}
where $E$ is expressed in \MeV, $R(E)$ is quoted in percent, $a$ represents the
stochastic term, and $b$ denotes the constant term. This is a useful pattern
for equations in the dissertation: define the model, label it, and immediately
explain the symbols in prose.

\section{Figure Pattern}

\figref{fig:example-energy-resolution} illustrates a standard presentation for
a measurement plot. The caption is self-contained, the axis labels carry their
units, and the discussion in the body text refers the reader to the key trend
rather than restating every plotted point. A good default workflow is to keep
numerical inputs in \code{data/}, generate publication figures into
\code{figures/generated/}, and include only the final artifact in LaTeX.

\begin{figure}[tbp]
  \centering
  \includegraphics[width=0.78\textwidth]{figures/generated/example_energy_resolution}
  \caption{Example energy-resolution measurement as a function of beam energy.
  Markers show simulated measurements with one-standard-deviation
  uncertainties, and the solid curve shows a fit to
  \eqnref{eq:example-resolution-model}.}
  \label{fig:example-energy-resolution}
\end{figure}

The figure is intentionally simple, but it already follows a publication-grade
pattern: consistent typography, restrained use of color, legible error bars,
and a caption that tells the reader what is being shown without turning into a
paragraph. The corresponding input data live in
\code{data/example_energy_resolution.csv}, and the figure is regenerated by
\code{scripts/generate_example_figure.py}.

\section{Table Pattern}

\tabref{tab:example-timing} shows a compact format for reporting summary
performance numbers. The table avoids vertical rules, moves units into the
column headers, and limits significant digits to the actual measurement
precision. For tables that are longer than a few lines, it is often cleaner to
place the environment in a dedicated file and include it with \verb|\input{}|
so the surrounding chapter text remains easy to read.

\input{tables/example_timing_summary}

The surrounding paragraph should interpret the table rather than duplicate it.
For example, \tabref{tab:example-timing} makes it immediately clear that the
template-fit configuration improves timing resolution relative to a leading-edge
discriminator while also preserving high efficiency.

\section{Cross-Reference Pattern}

The most readable scientific writing uses references to guide the reader across
the argument. A typical sentence might read as follows: the fit in
\figref{fig:example-energy-resolution} is consistent with the resolution model
introduced in \eqnref{eq:example-resolution-model}, while the comparison in
\tabref{tab:example-timing} summarizes the performance tradeoff between several
reconstruction choices. That pattern scales well across a full chapter because
it keeps the narrative anchored to specific evidence.

\bibliographystyle{unsrt}
\bibliography{bibliography/example_references}

\end{document}
EOF

write_if_needed "${playground_dir}/bibliography/example_references.bib" <<'EOF'
@article{agostinelli2003geant4,
  author = {Agostinelli, S. and others},
  title = {Geant4---a simulation toolkit},
  journal = {Nuclear Instruments and Methods in Physics Research Section A},
  volume = {506},
  number = {3},
  pages = {250--303},
  year = {2003},
  doi = {10.1016/S0168-9002(03)01368-8}
}

@article{brun1997root,
  author = {Brun, Rene and Rademakers, Fons},
  title = {ROOT---An object oriented data analysis framework},
  journal = {Nuclear Instruments and Methods in Physics Research Section A},
  volume = {389},
  number = {1-2},
  pages = {81--86},
  year = {1997},
  doi = {10.1016/S0168-9002(97)00048-X}
}

@book{knoll2010radiation,
  author = {Knoll, Glenn F.},
  title = {Radiation Detection and Measurement},
  edition = {4},
  publisher = {John Wiley \& Sons},
  address = {Hoboken, NJ},
  year = {2010}
}
EOF

write_if_needed "${playground_dir}/data/example_energy_resolution.csv" <<'EOF'
energy_mev,resolution_pct,resolution_err_pct
50,13.8,0.5
75,11.4,0.4
100,9.8,0.35
150,8.1,0.28
250,6.4,0.2
400,5.1,0.16
EOF

write_if_needed "${playground_dir}/tables/example_timing_summary.tex" <<'EOF'
\begin{table}[tbp]
  \centering
  \caption{Representative timing-performance summary for three reconstruction
  configurations. The quoted uncertainty is the run-to-run spread of the fitted
  timing resolution.}
  \label{tab:example-timing}
  \begin{tabular}{l S[table-format=2.0] S[table-format=1.3(2)] S[table-format=1.3]}
    \toprule
    Configuration & {Threshold [\si{\milli\volt}]} & {Resolution [\si{\nano\second}]} & {Efficiency} \\
    \midrule
    Leading-edge discriminator & 20 & 0.245(12) & 0.934 \\
    Constant-fraction discriminator & 30 & 0.181(10) & 0.961 \\
    Template fit & 35 & 0.132(8) & 0.978 \\
    \bottomrule
  \end{tabular}
\end{table}
EOF

write_if_needed "${playground_dir}/scripts/generate_example_figure.py" <<'EOF'
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.optimize import curve_fit


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "example_energy_resolution.csv"
OUTPUT_PATH = ROOT / "figures" / "generated" / "example_energy_resolution.pdf"


def resolution_model(energy_mev: np.ndarray, stochastic: float, constant: float) -> np.ndarray:
    return np.sqrt((stochastic / np.sqrt(energy_mev)) ** 2 + constant**2)


def main() -> None:
    data = pd.read_csv(DATA_PATH)

    fit_parameters, _ = curve_fit(
        resolution_model,
        data["energy_mev"],
        data["resolution_pct"],
        sigma=data["resolution_err_pct"],
        absolute_sigma=True,
        p0=(95.0, 2.5),
    )

    energy_grid = np.linspace(data["energy_mev"].min(), data["energy_mev"].max(), 500)
    fit_curve = resolution_model(energy_grid, *fit_parameters)

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.size": 12,
            "axes.labelsize": 12,
            "axes.titlesize": 12,
            "legend.fontsize": 10,
            "xtick.labelsize": 11,
            "ytick.labelsize": 11,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )

    figure, axis = plt.subplots(figsize=(6.4, 4.4), constrained_layout=True)

    axis.errorbar(
        data["energy_mev"],
        data["resolution_pct"],
        yerr=data["resolution_err_pct"],
        fmt="o",
        color="#1f4e79",
        markerfacecolor="#1f4e79",
        markeredgecolor="white",
        markeredgewidth=0.8,
        capsize=3,
        linewidth=1.2,
        label="Measured points",
    )
    axis.plot(
        energy_grid,
        fit_curve,
        color="#b44b20",
        linewidth=2.0,
        label="Fit to resolution model",
    )

    axis.set_xlabel("Beam energy [MeV]")
    axis.set_ylabel("Energy resolution [%]")
    axis.set_xlim(35, 415)
    axis.set_ylim(4.0, 15.5)
    axis.grid(True, which="major", color="#d9d9d9", linewidth=0.7)
    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)

    stochastic, constant = fit_parameters
    axis.text(
        0.04,
        0.95,
        (
            r"$R(E)=\sqrt{(a/\sqrt{E})^2+b^2}$" "\n"
            rf"$a={stochastic:.1f}$, $b={constant:.2f}$"
        ),
        transform=axis.transAxes,
        va="top",
        ha="left",
        bbox={"boxstyle": "round,pad=0.3", "facecolor": "white", "edgecolor": "#c0c0c0"},
    )
    axis.legend(frameon=False, loc="upper right")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(OUTPUT_PATH, bbox_inches="tight")


if __name__ == "__main__":
    main()
EOF

chmod +x "${playground_dir}/scripts/generate_example_figure.py"

echo "Playground ready at: ${playground_dir}"
if [[ "${overwrite}" -eq 0 ]]; then
  echo "Existing playground files were left untouched."
else
  echo "Playground files were refreshed."
fi
